### ISSUE TITLE
Add CSS to disable interpolation when scaling Canvas element

### ISSUE THREAD

**Issue by passiomatic** [passiomatic/mage-city#6]
Discussion:
https://stackoverflow.com/questions/7615009/disable-interpolation-when-scaling-a-canvas/7665647#7665647

Relevant CSS:

```css
canvas {
  image-rendering: optimizeSpeed;             /* Older versions of FF          */
  image-rendering: -moz-crisp-edges;          /* FF 6.0+                       */
  image-rendering: -webkit-optimize-contrast; /* Safari                        */
  image-rendering: -o-crisp-edges;            /* OS X & Windows Opera (12.02+) */
  image-rendering: pixelated;                 /* Awesome future-browsers       */
  -ms-interpolation-mode: nearest-neighbor;   /* IE                            */
}
```
